= OOAD Project 2
Michael Metz <mime9599@colorado.edu>; Sam Goto <osgo1115@colorado.edu>
June 9, 2022
:doctype: book
:toc:
:icons: font
:url-quickref: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

== Part One

[]
. What are three ways modern Java interfaces differ from a traditional OO interface design that
describes only function signatures and return types to be implemented? Provide a Java code example of each.
+
    * _(Note: Interface Segregation Principle)_ 
    * _(Note: Single Responsibility Principle)_
    * *Default Method* - allows its implementation classes to invoke the method without implementing it, and it can be overridden.
    * *Static Method* - allows its implementation classes to invoke the method without implementing it, however it cannot be overridden.
    * *Lamda expresions*  #TO DO
+
.Example
[source,java]
----
interface Animal {
   // Default method: This can be invoked in implementing classes, and can be overridden
   default void makeSound() {
      Ssytem.out.println("###");
   }
   
   // Static method: This method cannot be overridden
   static void eat() {
      System.out.println("Yum yum...");
   }
}

----

. Describe the differences and relationship between abstraction and encapsulation. Provide a Java
code example that illustrates the difference. 
+
   The main difference between abstraction and encapsulation is that abstraction is used to only show relevant information to hide implementation details whereas encapsulation is used to hide and protect data by limiting access to some specific data.


+
.Code Example
[source,java]  
---- 
// --------------Abstraction---------------
abstract class Computer {
   ...
   // enforces the child classes to have the Boot method
   public void Boot() {
      // Do stuff to boot up the computer
   }
   
   ...
}

public class MacBook extends Computer {
   // extending the Computer abstract class, thus the Boot method can be called
   Boot();
}


// -------------Encapsulation--------------
public class Student() {
   // encapsulate the name, thus it'll only be accesible from the getter and setter defined below
   private String name;
   
   /**
   * Constructor
   * @param name
   */
   Student(String name) {
      this.name = name;
   }
   
   
   /**
   *
   * @return the name 
   */
   public String getName() {
      return name;
   }
   /**
   *  sets the name
   *  @param name
   */
   public setName(String name) {
      this.name = name;
   }
}
----

